### ISSUE TITLE
癫痫预测

### ISSUE THREAD

**Issue by wangyumo85** [JonathanCauchi/Seizure-Detection-Prediction#1]
运行癫痫预测出现以下错误该怎么处理
错误使用 ClassificationSVM (line 273)
No data remaining after all rows with NaNs are removed.

出错 classreg.learning.FitTemplate/fit (line 258)
            [varargout{1:nargout}] = this.MakeFitObject(X,Y,W,this.ModelParams,fitArgs{:});

出错 ClassificationSVM.fit (line 240)
            this = fit(temp,X,Y);

出错 fitcsvm (line 370)
    obj = ClassificationSVM.fit(X,Y,RemainingArgs{:});

出错 run (line 32)
clfSvm =fitcsvm (dataTrain.feature_norm, dataTrain.class,'Standardize',false,...

**Comment by JonathanCauchi** [comment]
@wangyumo85 It's been a while since I worked on this project. If you need help with it, send me an email jonathancauchi2796@gmail.com :)
