### ISSUE TITLE
 I ask for advice to you a few questions

### ISSUE THREAD

**Issue by YANKT** [JonathanCauchi/Seizure-Detection-Prediction#2]
Hi  JonathanCauchi:
Thank you for reading!
I am a Grade 1 master at Qufu Normal University, China.
I need your hlep 🙂
Seizure-Prediction project
1.In the read_data.m file, 'addpath([pwd '/physio_pack'])', what is physio_pack? Does it mean wfdb tool-box?
![3a79b571d20deed5bbcdb7a9d2a1fb6](https://user-images.githubusercontent.com/48278536/163670101-242fb8d3-e3f9-4c60-96b5-fbc8171191b3.png)
2.After running for a while, there will be an error as shown in the figure below, I don't know why.Function or variable 'channels' not recognized.

![3a79b571d20deed5bbcdb7a9d2a1fb6](https://user-images.githubusercontent.com/48278536/163670144-33c785d3-f32f-40ca-8bba-797324449c87.png)
![4934e37c9d487705f64738a437ec7c9](https://user-images.githubusercontent.com/48278536/163670149-6f1fc35e-f011-4e0d-8ad6-95541d301e00.png)

**Comment by JonathanCauchi** [comment]
Its been a while since I worked on this project. I did not upload the toolbox as it's too large for GitHub. Furthermore, it is of note that the code uploaded here was not the final working code. Here's a link to the actual folder on Google Drive: https://drive.google.com/file/d/153hpY6lwYz1Jj3gj2z35L1p7s-lgi8tx/view?usp=sharing

Hope that helps!

**Comment by YANKT** [comment]
Thank you for your reply. The Google Drive link cannot be opened normally. Could you please share it with me again? Thank you.

**Comment by JonathanCauchi** [comment]
You should be able to download: https://drive.google.com/drive/folders/152t9RtsFT8uiOJmqrA2FG8p3GwJTCthr?usp=sharing

**Comment by YANKT** [comment]
Unfortunately, the link folder you shared with me is empty :(
https://drive.google.com/drive/folders/152t9RtsFT8uiOJmqrA2FG8p3GwJTCthr?usp=sharing

**Comment by JonathanCauchi** [comment]
You need to download the zip file. Please stop sending emails now as I see
you're incompetent

**Comment by claupetcu14** [comment]
Hello!
Thank you for reading!
I am a Grade 1 master at POLITEHNICA București National University for Science and Technology, Romania.
I need your hlep 🙂
I am working a lot to make this code work, but still so many errors coming out and I just can't deal with them. Same as the guy above. Can you help me, please?
